spring.application.name=raccoon-cash-api

spring.datasource.url=jdbc:postgresql://127.0.0.1:2805/raccoon_cash_db
spring.datasource.username=postgres
spring.datasource.password=AmoaRengoku123
spring.datasource.driver-class-name=org.postgresql.Driver

# Usamos 'update' para que la base de datos sea persistente.
# Ya no se borrara nada al reiniciar.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# No se cargan cuentas, transacciones ni otros datos financieros iniciales.
# Solo se carga el catalogo base de categorias para poder registrar movimientos.
raccoon-cash.data.seed-default-categories=true

server.port=8080
